server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1q2w3e4r
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true
    open-in-view: false

  security:
    oauth2:
        jwt:
          signkey: jwt-token-secret

logging:
  level:
    org.hibernate.type: trace

